import Set from "./set";

function Settings(){

    return(<div className="case">
    <div className="flex-column">

        <Set path = "bookingstatus" title = "Booking Status"/>   
        <Set path = "roomstatus" title = "Room Status"/>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
        <Set path = "paymentstatus" title = "Payment Status"/>   
        <Set path = "paymenttypes" title = "Payment Types"/>
        <Set path = "reservationstatus" title = "Reservation Status"/> 
        <Set path = "roomtypes" title = "Room Types"/>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    
    </div>
    </div>)
}
export default Settings;