import Set from "../Admin/Set";

function Settings(){

    return(<>
        <Set path = "bookingstatus" title = "Booking Status"/>   
        <Set path = "roomstatus" title = "Room Status"/>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
        <Set path = "paymentstatus" title = "Payment Status"/>   
        <Set path = "paymenttypes" title = "Payment Types"/>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       

    </>)
}
export default Settings;